"""A skeletal blackboard system.

The library supplies the board, the shared structure through which
independent agents contribute to one result, and the control component's
write path, notification dispatch, and run closure: a write made through
it passes admission before the board sequences it, an admitted register
write notifies every other registered agent, and the run closes in one of
four recorded states. The public surface is the set of names in
``__all__``; every other name is internal.
"""

from blackboard._board import (
    BlackboardError,
    Board,
    BoardChange,
    Conflict,
    Contribution,
    DuplicateRegionError,
    Level,
    RegionKindError,
    Register,
    RegisterState,
    UndeclaredRegionError,
    UnsetRegisterError,
    Written,
)
from blackboard._clock import Clock, ManualClock, ScheduledCall, SystemClock
from blackboard._control import (
    Aborted,
    Accept,
    Accepted,
    AdmissionRule,
    Agent,
    AuditEvent,
    BoardReader,
    BudgetExhausted,
    BudgetKind,
    BudgetReached,
    Complete,
    DeadlineExtended,
    DuplicateAgentError,
    FinishedWithFailures,
    Notification,
    NotificationAcknowledged,
    NotificationDispatched,
    NotificationId,
    PresumedFailed,
    ProposedContribution,
    ProposedRegisterWrite,
    ProposedWrite,
    Reject,
    Rejected,
    RejectionCause,
    RunBudgets,
    RunClosed,
    RunClosedError,
    RunOutcome,
    TerminationDecision,
    TerminationPredicate,
    UnknownNotificationError,
    WakeCapReached,
    WriteAccepted,
    WriteRejected,
)

__all__ = [
    "Aborted",
    "Accept",
    "Accepted",
    "AdmissionRule",
    "Agent",
    "AuditEvent",
    "BlackboardError",
    "Board",
    "BoardChange",
    "BoardReader",
    "BudgetExhausted",
    "BudgetKind",
    "BudgetReached",
    "Clock",
    "Complete",
    "Conflict",
    "Contribution",
    "DeadlineExtended",
    "DuplicateAgentError",
    "DuplicateRegionError",
    "FinishedWithFailures",
    "Level",
    "ManualClock",
    "Notification",
    "NotificationAcknowledged",
    "NotificationDispatched",
    "NotificationId",
    "PresumedFailed",
    "ProposedContribution",
    "ProposedRegisterWrite",
    "ProposedWrite",
    "RegionKindError",
    "Register",
    "RegisterState",
    "Reject",
    "Rejected",
    "RejectionCause",
    "RunBudgets",
    "RunClosed",
    "RunClosedError",
    "RunOutcome",
    "ScheduledCall",
    "SystemClock",
    "TerminationDecision",
    "TerminationPredicate",
    "UndeclaredRegionError",
    "UnknownNotificationError",
    "UnsetRegisterError",
    "WakeCapReached",
    "WriteAccepted",
    "WriteRejected",
    "Written",
]
